### ISSUE TITLE
Photo size correction is required.

### ISSUE THREAD

**Issue by taxtist** [PedityOfficial/Pedity-Platform#1]
![1](https://user-images.githubusercontent.com/18159654/48403254-dd4d8a80-e770-11e8-87cb-bd651c02e889.jpg)
![2](https://user-images.githubusercontent.com/18159654/48403255-dd4d8a80-e770-11e8-9ea9-2f7beb071070.jpg)

Photo size correction is required.

**Comment by Pedity-Luffy** [comment]
Fixed in 0.1.3
