### ISSUE TITLE
listing page problem : preview

### ISSUE THREAD

**Issue by taxtist** [PedityOfficial/Pedity-Platform#4]
![스크린샷 2019-03-27 오전 6 25 55](https://user-images.githubusercontent.com/18159654/55034683-62b74480-5059-11e9-903c-6c38f116cd32.png)

**Comment by taxtist** [comment]
https://pedity.com/article/7f7d2cb82c294400ed943e9cbab3eb8c3439f66716444868a89d261393cddf94

**Comment by Pedity-Luffy** [comment]
This issue is fixed.
